# Fundamentals

**TensorFlow** is an open-source end-to-end machine learning library for preprocessing data, modelling data and serving models.Rather than building machine learning and deep learning models from scratch, tensorflow contains many of the most common machine learning functions one might need. 

While TensorFlow is vast, the main premise is simple: turn data into numbers (tensors) and build machine learning algorithms to find patterns in them.

In [170]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.9.1


## tf.constant()

In general, we won't create tensors ourselfs. This is because TensorFlow has modules built-in which are able to read data sources and automatically convert them to tensors and then later on, neural network models will process these for us. 

But for now, because we're getting familar with tensors themselves and how to manipulate them, we'll see how we can create them ourselves.

In [46]:
# scalar constant (rank 0 tensor)
scalar = tf.constant(7, name="scalar", dtype=tf.int32) # default dtype: int32 or float32 datatype.
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [49]:
# vector constant (rank 1 tensor)
vector = tf.constant([7.,10.], name="vector", dtype=tf.float64)
vector

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([ 7., 10.])>

In [64]:
# 2-D matrix constant (rank 2 tensor)
matrix_2d = tf.constant([[7,10],
                         [10,7]], name="2d_matrix", dtype=tf.int32)
matrix_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10,  7]], dtype=int32)>

In [65]:
# 3-D matrix constant (rank 3 tensor)
matrix_3d = tf.constant([[[7,10],
                          [10,7]],
                         [[10,7],
                          [7,10]]], name="3d_matrix", dtype=tf.int32)
matrix_3d

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 7, 10],
        [10,  7]],

       [[10,  7],
        [ 7, 10]]], dtype=int32)>

### Changing The Datatype Of A Tensor

Sometimes we'll want to alter the default datatype of a tensor. This is common when we want to compute using less precision (e.g. 16-bit floating point numbers vs. 32-bit floating point numbers).

Computing with less precision is useful on devices with less computing capacity such as mobile devices (because the less bits, the less space the computations require).

In [165]:
# Create a new tensor with default datatype (int32)
scalar_float_32 = tf.cast(scalar, dtype=tf.float32)
scalar_float_32

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

### Tensor Attributes

Tensors carry their own **attributes** like:
* **Shape**: The length (number of elements) of each of the dimensions of a tensor.
* **Rank**: The number of tensor dimensions.
* **Axis or Dimension**: A particular dimension of a tensor.
* **Size**: The total number of items in the tensor.

In [136]:
# various tensor attributes
print("Datatype of every element:", matrix_3d.dtype)
print("Number of dimensions (rank):", matrix_3d.ndim)
print("Shape of tensor:", matrix_3d.shape)
print("Total number of elements (2*2*2):", tf.size(matrix_3d).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'int32'>
Number of dimensions (rank): 3
Shape of tensor: (2, 2, 2)
Total number of elements (2*2*2): tf.Tensor(8, shape=(), dtype=int32)


We can **index** tensors just like Python lists.

In [149]:
# indexing a tensor
matrix_3d[1, 0:, :1]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[10],
       [ 7]], dtype=int32)>

### Other Ways To Create Tensors

There are some other ways to create constant tensors.

In [71]:
# a tensor of given dimensions full with 0's and 1's!
zeros = tf.zeros((2, 3))   
ones = tf.ones((3,2))
zeros, ones

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>)

In [150]:
# general form
sevens = tf.fill(dims = (2, 3), value = 7)
tens = tf.fill(dims = (3, 2), value = 10)
sevens, tens

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[7, 7, 7],
        [7, 7, 7]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10, 10],
        [10, 10],
        [10, 10]], dtype=int32)>)

In [126]:
# range (limit is not included)
ran = tf.range(start = 3, limit=18, delta=3)
ran

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 3,  6,  9, 12, 15], dtype=int32)>

In [127]:
# sequence of numbers
linspace = tf.linspace(start = 10.0, stop = 13.0, num = 4)
linspace

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([10., 11., 12., 13.], dtype=float32)>

### Tensor Operations

We can perform many of the basic mathematical operations directly on tensors using Pyhton operators. (Since we used tf.constant(), the original tensor is unchanged (the addition gets done on a copy).

In [128]:
# we can operate with values to a tensor using the corresponding operator
tensor = tf.constant([[10, 7], 
                      [3, 4]])

tensor + 10, tensor * 10, tensor - 10, tensor /10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[1. , 0.7],
        [0.3, 0.4]])>)

We can also use the following function for the basic operations.

In [159]:
a = tf.constant([[3, 6]])
b = tf.constant([[2, 2]])

# element wise addition
addition = tf.add(a,b)

# element wise multiplication
multiplication = tf.multiply(a,b)

# matrix multiplication (reshaping needed)
matrix_multiplication = tf.matmul(tf.reshape(a, [1, 2]), tf.reshape(b, [2, 1]))

# element wise division
division = tf.divide(a, b)

# element wise rise to power
power = tf.pow(a,b)

addition, multiplication, matrix_multiplication, division, power

(<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[5, 8]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[ 6, 12]], dtype=int32)>,
 <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[18]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2), dtype=float64, numpy=array([[1.5, 3. ]])>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[ 9, 36]], dtype=int32)>)

Some more basic operation functions.

In [168]:
# square
square = tf.square(a)

# square root
sqrt = tf.sqrt(tf.cast(a, tf.float32))

# log
log = tf.math.log(tf.cast(a, tf.float32))

# absolute values
absolute_value = tf.abs(a)

# find the minimum
reduce_min = tf.reduce_min(a)

# find the minimum element position
argmin = tf.argmin(a)

# find the maximum
reduce_max = tf.reduce_max(a)

# find the maximum element position
argmax = tf.argmax(a)

# find the mean
reduce_mean = tf.reduce_mean(a)

# find the sum
reduce_sum = tf.reduce_sum(a)

square, sqrt, log, absolute_value, reduce_min, argmin, reduce_max, argmax, reduce_mean, reduce_sum

(<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[ 9, 36]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1.7320508, 2.4494898]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1.0986123, 1.7917595]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[3, 6]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 0])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>,
 <tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 0])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>)

If you have a tensor of indicies and would like to **one-hot encode** it, you can use tf.one_hot(). You should also specify the depth parameter (the level which you want to one-hot encode to).

In [163]:
some_list = [0, 1, 2, 3]

# one hot encodingb
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

If you need to remove single-dimensions from a tensor (dimensions with size 1), we can use **squeeze** it, i.e  remove all dimensions of 1 from a tensor.

In [172]:
c = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
c

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
array([[[[[88, 37, 20, 20, 24, 49, 45, 89, 73, 77, 56, 13, 97, 55, 12,
           65, 90,  4, 97, 18, 26,  9, 73, 11,  4, 66, 28, 43, 33, 77,
            6, 42,  1, 97,  7, 25, 98, 78,  6, 15, 29, 84, 89, 40, 58,
           38,  7, 42, 60, 73]]]]])>

In [173]:
# squeeze tensor (remove all 1 dimensions)
c_squeezed = tf.squeeze(c)
c_squeezed

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([88, 37, 20, 20, 24, 49, 45, 89, 73, 77, 56, 13, 97, 55, 12, 65, 90,
        4, 97, 18, 26,  9, 73, 11,  4, 66, 28, 43, 33, 77,  6, 42,  1, 97,
        7, 25, 98, 78,  6, 15, 29, 84, 89, 40, 58, 38,  7, 42, 60, 73])>

## tf.Variable()

The difference between **tf.Variable()** and **tf.constant()** is tensors created with tf.constant() are immutable (can't be changed, can only be used to create a new tensor), where as, tensors created with tf.Variable() are mutable (can be changed).

In [87]:
# scalar variable
scalar = tf.Variable(2, name="scalar")

# vector variable
vector = tf.Variable([2, 3], name="vector")

# matrix variable
matrix = tf.Variable([
    [0, 1], 
    [2, 3]
], name="matrix")

To change an element of a tf.Variable() tensor requires the assign() method.

In [42]:
# assign operation
scalar.assign(3)

<tf.Variable 'scalar:0' shape=() dtype=int32, numpy=3>

## tf.random()

Random tensors are tensors of some abitrary size which contain random numbers. This is what neural networks use to intialize their weights that they're trying to learn in the data.

In [116]:
# global level seed (for reproducibility)
tf.random.set_seed(42)

In [125]:
# random tensor generator (local level seed)
random_tensor = tf.random.Generator.from_seed(42)

In [118]:
# random tensor from uniform distribution
random_tensor_uniform = random_tensor.uniform(shape=(3,2))
random_tensor_uniform

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [119]:
# random tensor from normal distribution
random_tensor_normal = random_tensor.normal(shape=(2,3))
random_tensor_normal

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.17522676,  0.71105534,  0.54882437],
       [ 0.14896014, -0.54757965,  0.61634356]], dtype=float32)>

Random can also shuffle a tensor.

In [124]:
# randomly shuffle a tensor
tensor = tf.constant([[7,10], [2,3], [5,4]])
tf.random.shuffle(tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 5,  4],
       [ 2,  3]], dtype=int32)>